import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: ["./src/**/*.{js,ts,jsx,tsx,mdx}"],
  theme: {
    extend: {
      colors: {
        "tertiary-container": "#009bd1",
        "surface-bright": "#37393d",
        "surface-dim": "#111317",
        error: "#ffb4ab",
        background: "#111317",
        "on-error": "#690005",
        "tertiary-fixed-dim": "#7bd0ff",
        "on-primary-fixed-variant": "#005137",
        "on-tertiary-fixed-variant": "#004c69",
        "on-tertiary-fixed": "#001e2c",
        "primary-fixed-dim": "#68dba9",
        "secondary-fixed-dim": "#b7c8e1",
        "on-tertiary": "#00354a",
        tertiary: "#7bd0ff",
        "surface-container-low": "#1a1c1f",
        "on-primary-fixed": "#002114",
        "tertiary-fixed": "#c4e7ff",
        "on-surface-variant": "#bccac0",
        "secondary-fixed": "#d3e4fe",
        "inverse-primary": "#006c4a",
        primary: "#68dba9",
        "surface-container-high": "#282a2d",
        "on-primary": "#003825",
        "primary-fixed": "#85f8c4",
        "surface-tint": "#68dba9",
        "inverse-surface": "#e2e2e6",
        surface: "#111317",
        "surface-container": "#1e2023",
        "on-secondary-fixed": "#0b1c30",
        "outline-variant": "#3d4a42",
        "surface-variant": "#333538",
        secondary: "#b7c8e1",
        "on-background": "#e2e2e6",
        "surface-container-lowest": "#0c0e11",
        "on-secondary": "#213145",
        "primary-container": "#25a475",
        "surface-container-highest": "#333538",
        "on-error-container": "#ffdad6",
        "on-secondary-fixed-variant": "#38485d",
        outline: "#87948b",
        "on-surface": "#e2e2e6",
        "secondary-container": "#3a4a5f",
        "on-tertiary-container": "#002d40",
        "on-secondary-container": "#a9bad3",
        "error-container": "#93000a",
        "on-primary-container": "#00311f",
        "inverse-on-surface": "#2f3034",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "space-lg": "1.5rem",
        margin: "1.5rem",
        "margin-mobile": "1rem",
        "gutter-mobile": "0.75rem",
        "space-xl": "2rem",
        "space-md": "1rem",
        gutter: "1rem",
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
      },
      fontFamily: {
        "headline-sm": ["var(--font-headline)", "Hanken Grotesk", "system-ui", "sans-serif"],
        "body-sm": ["var(--font-body)", "Geist", "system-ui", "sans-serif"],
        "display-hero": ["var(--font-headline)", "Hanken Grotesk", "system-ui", "sans-serif"],
        "headline-lg-mobile": ["var(--font-headline)", "Hanken Grotesk", "system-ui", "sans-serif"],
        "display-hero-mobile": ["var(--font-headline)", "Hanken Grotesk", "system-ui", "sans-serif"],
        "numeric-list": ["var(--font-body)", "Geist", "system-ui", "sans-serif"],
        "label-sm": ["var(--font-body)", "Geist", "system-ui", "sans-serif"],
        "label-md": ["var(--font-body)", "Geist", "system-ui", "sans-serif"],
        "body-lg": ["var(--font-body)", "Geist", "system-ui", "sans-serif"],
        "numeric-hero-mobile": ["var(--font-body)", "Geist", "system-ui", "sans-serif"],
        "headline-lg": ["var(--font-headline)", "Hanken Grotesk", "system-ui", "sans-serif"],
        "headline-md": ["var(--font-headline)", "Hanken Grotesk", "system-ui", "sans-serif"],
        "numeric-card": ["var(--font-body)", "Geist", "system-ui", "sans-serif"],
        "body-md": ["var(--font-body)", "Geist", "system-ui", "sans-serif"],
        "numeric-hero": ["var(--font-body)", "Geist", "system-ui", "sans-serif"],
      },
      fontSize: {
        "headline-sm": ["18px", { lineHeight: "24px", letterSpacing: "-0.01em", fontWeight: "500" }],
        "body-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.005em", fontWeight: "400" }],
        "display-hero": ["48px", { lineHeight: "52px", letterSpacing: "-0.03em", fontWeight: "600" }],
        "headline-lg-mobile": ["26px", { lineHeight: "32px", letterSpacing: "-0.015em", fontWeight: "600" }],
        "display-hero-mobile": ["36px", { lineHeight: "40px", letterSpacing: "-0.025em", fontWeight: "600" }],
        "numeric-list": ["15px", { lineHeight: "20px", letterSpacing: "0em", fontWeight: "500" }],
        "label-sm": ["11px", { lineHeight: "14px", letterSpacing: "0.03em", fontWeight: "500" }],
        "label-md": ["13px", { lineHeight: "16px", letterSpacing: "0.01em", fontWeight: "500" }],
        "body-lg": ["16px", { lineHeight: "24px", letterSpacing: "-0.005em", fontWeight: "400" }],
        "numeric-hero-mobile": ["32px", { lineHeight: "36px", letterSpacing: "-0.015em", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "38px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-md": ["22px", { lineHeight: "28px", letterSpacing: "-0.015em", fontWeight: "500" }],
        "numeric-card": ["22px", { lineHeight: "26px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-md": ["14px", { lineHeight: "20px", letterSpacing: "0em", fontWeight: "400" }],
        "numeric-hero": ["40px", { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "600" }],
      },
      boxShadow: {
        "glow-primary": "0 0 12px rgba(104, 219, 169, 0.35)",
        "glow-primary-lg": "0 8px 24px -4px rgba(37, 164, 117, 0.55)",
        "glow-primary-soft": "0 8px 24px -4px rgba(104, 219, 169, 0.4)",
      },
      keyframes: {
        "fade-in-up": {
          "0%": { opacity: "0", transform: "translateY(8px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
      },
      animation: {
        "fade-in-up": "fade-in-up 0.3s ease-out",
      },
    },
  },
  plugins: [],
};

export default config;